in BINFUN
in COLLECTIONS

--- causes a crash (due to the use of theory-views and multi-level binding in ARROW" : see email from Steven)
--- fmod BFUN-ITE{X :: ITERABLE, Y :: TRIV} is
---  protecting BINFUN{Iterable, TRIV}{X, Y} .
--- ... 
--- endfm

--- pattern suggested by Steven (instead of theory-view Iterable)
fmod DUMMY-ITE{X :: ITERABLE} is
endfm

view Iterable{X :: ITERABLE} from TRIV to DUMMY-ITE{X} is
  sort Elt to X$Elt .
endv


fmod FOLD-ITE{X :: ITERABLE, Y :: TRIV} is
  protecting BINFUN{Iterable{X}, Y} * (sort BinFun{Iterable{X},Y} to BinFun{X,Y}) . --- functions!!
  op fold : BinFun{X,Y} Y$Elt X$Coll -> [Y$Elt] .

  var f   : BinFun{X,Y} .
  var acc : Y$Elt .
  var l   : X$Coll .

  eq fold(f, acc, X$nil) = acc .
  eq fold(f, acc, l)     = fold(f, f get(l) acc, remainder(l)) .
endfm

--- causes a crash (same reason as above)
--- fmod FOLD-COLL{X :: COLLECTION, Y :: TRIV} is
---   protecting FOLD-ITE{IteColl, TRIV}{X, Y} * (sort Arrow{IteColl,TRIV}{X,Y} to Arrow{X,Y},
---     sort BinFun{IteColl,TRIV}{X,Y} to BinFun{X,Y},
---     sort Arrow{TRIV,TRIV}{Y,Y} to  Arrow{Y,Y}, sort Fun{TRIV}{Y} to Fun{Y}) .
---  endfm

--- we use the same pattern (not to use the theory-view IteColl)
fmod DUMMY-COLL{X :: COLLECTION} is
endfm

view Collection{X :: COLLECTION} from TRIV to DUMMY-COLL{X} is
  sort Elt to X$Elt .
endv

fmod FOLD-COLL{X :: COLLECTION, Y :: TRIV} is
  protecting BINFUN{Collection{X}, Y} * (sort BinFun{Collection{X},Y} to BinFun{X,Y}).
   op fold : BinFun{X,Y} Y$Elt X$Coll -> [Y$Elt] .

  var f   : BinFun{X,Y} .
  var acc : Y$Elt .
  var l   : X$Coll .
  var e   : X$Elt .

  eq fold(f, acc, X$nil) = acc .
  eq fold(f, acc, l e)   = fold(f, f e acc, l) .
endfm


--- ALTERNATIVE APPROACH (using AS-COLLECTION) ---

fmod DUMMY-ASCOLL{X :: AS-COLLECTION} is
endfm

view AsColl{X :: AS-COLLECTION} from TRIV to DUMMY-ASCOLL{X} is
  sort Elt to X$Elt . 
endv

fmod FOLD-ASCOLL{X :: AS-COLLECTION, Y :: TRIV} is
   protecting BINFUN{AsColl{X}, Y} * (sort BinFun{AsColl{X}, Y} to BinFun{X,Y}) .
   op fold : BinFun{X,Y} Y$Elt X$Iterable -> [Y$Elt] .
   var f   : BinFun{X,Y} .
   var acc : Y$Elt .
   var l   : X$Iterable  .
   var l'  : X$Coll .
   var e   : X$Elt .
   eq fold(f, acc, l) = $fold(f, acc, iterator(l)) .
   op $fold : BinFun{X,Y} Y$Elt X$Coll -> [Y$Elt] .
   eq $fold(f, acc, X$nil) = acc .
   eq $fold(f, acc, l' e)  = $fold(f, f e acc, l') .
endfm

view ASCOLL{X :: COLLECTION} from AS-COLLECTION to DUMMY-COLL{X} is
  sort Elt to X$Elt . 
  sort Coll to X$Coll . 
  sort Iterable to X$Coll .
  op nil to X$nil .
  op iterator(C:Iterable) to term C:X$Coll .
endv

--- this version is defined starting from FOLD-ASCOLL
fmod FOLD-COLL'{X :: COLLECTION, Y :: TRIV} is
   protecting FOLD-ASCOLL{ASCOLL{X}, Y} * (sort BinFun{ASCOLL{X},Y} to BinFun{X,Y}) .
endfm
